### ISSUE TITLE
FAD2 Crash

### ISSUE THREAD

**Issue by freewee** [OleAlbers/fad2#10]
`Program-Version: 2.0.3.34137`
Hi
I' m using FAD2 since a while, and the last build correct the problems I had...
Fine, but I realise yhat I have a big problem, on 2 PCs W7 64b.
This occures when the card have  too many pictures (how many???):
For example, I have 230 pictures on the card, I want to download them on a PC where they didn't have been downloaded yet: No problem. But if I take an other shot on this card, and want to download it on the same PC, then crash of FAD2...
I didn' had this problem when I had less pictures on the card (how many???).
I reinstall, delete conf and log files, but it is the same.
What test could I make to give you further indications? 
Dominique Breton
[fad2.txt](https://github.com/OleAlbers/fad2/files/288339/fad2.txt)

**Comment by freewee** [comment]
Only for confirming that I have no problem when I have less pictures on the card!
Dominique

**Comment by Guacam-Ole** [comment]
The log shows that the connection is lost. So most likely the webserver on the sdcard just crashed. I don't think I can do much about that

**Comment by freewee** [comment]
Thank you
When I have the problem, I go back to FAD1, that still works in this case!
Dominique
