### ISSUE TITLE
Access denied to config file during saving

### ISSUE THREAD

**Issue by SensorsIot** [OleAlbers/fad2#7]
I try to use FAD2 (I was a user of your first edition). I configured my flashairs (tried 8GB and 32GB versions on windows 10 and 7) and loaded the configuration. I get the three new tabs and the fields are filled out (e.g. Card ID).
When I try to save (I run it in administration mode to be sure), I get an error (see attachments). I can read and write the config file by an editor or by the Toshiba Flashair tool without any problems.

![15-05-_2016_08-18-14](https://cloud.githubusercontent.com/assets/13062557/15272389/0faf6c5c-1a76-11e6-9955-77bf6fdfec4c.jpg)
![15-05-_2016_08-18-50](https://cloud.githubusercontent.com/assets/13062557/15272390/0fafc058-1a76-11e6-8b62-9959219dd099.jpg)
![15-05-_2016_08-19-02](https://cloud.githubusercontent.com/assets/13062557/15272391/0fb10d46-1a76-11e6-8cc2-b80419f026d2.jpg)
![15-05-_2016_08-19-19](https://cloud.githubusercontent.com/assets/13062557/15272392/0fb25a5c-1a76-11e6-93a0-be30d3c9817c.jpg)

**Comment by Guacam-Ole** [comment]
Hmm. Looks like your Windows is not allowing the program to write to the card. 

If you got any other drive (D: or above) you could try to create a directory SD_WLAN there and put the config there and copy it back after it has been changed.

But I will also add something to catch that error and offer the possibility to save it elsewhere.

**Comment by SensorsIot** [comment]
Thanks for the fast answer. I played around and when I removed the hidden file attribute it worked!
Now, I am able to download files. Great. Thank you for your work!
Just three small remarks: 
1. I tried to change the name of my flashair to "camera" and I think, the flashair Url was not saved
2. I use a Sony camcorder and the video file extensions are MTS. I have to select "all files" and then it works
3. Because I film and work in parallel on the computer it would be great to have an auto mode which runs regularly in the background without any announcement (or just exceptions)

**Comment by SensorsIot** [comment]
Just an addition: The field flashair URL is saved, but not displayed.

**Comment by Guacam-Ole** [comment]
Thanks for the test. The "Hidden" attribute helped finding a solution on the net. Will include that

**Comment by Guacam-Ole** [comment]
The Auto-Mode is planned - but I don't know when I find time to implement it.

**Comment by SensorsIot** [comment]
Great. I already used it yesterday with big success. It takes a while to copy videos over the net (I get about 1 MByte transfer rate. But because it runs "unattended" I was able to do something else during this time.
